---
- name: Basic VM Linux playbook
  hosts: vms
  become: true

  tasks:
    - name: Upgrade the OS
      ansible.builtin.apt:
        upgrade: dist
        update_cache: true
    - name: Install git,htop, curl
      ansible.builtin.apt:
        pkg:
          - git
          - htop
          - curl
