---
- name: SSH Hardening
  hosts: vms
  become: true

  tasks:
    - name: Copy 00-hardening.conf
      ansible.builtin.copy:
        src: 00-hardening.conf
        dest: /etc/ssh/sshd_config.d/
        mode: "0644"
        owner: root
        group: root
        validate: /usr/sbin/sshd -t -f %s
      notify:
        - Restart ssh daemon

  handlers:
    - name: Restart ssh daemon
      ansible.builtin.service:
        name: ssh
        state: restarted
